<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageVersionOverrideEnabled>true</CentralPackageVersionOverrideEnabled>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <XperienceMinimumVersion>30.11.0</XperienceMinimumVersion>
    <XperienceLatestVersion>31.7.2</XperienceLatestVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Kentico.Xperience.Admin" Version="$(XperienceMinimumVersion)" />
    <PackageVersion Include="Kentico.Xperience.WebApp" Version="$(XperienceMinimumVersion)" />
    <PackageVersion Include="kentico.xperience.azurestorage" Version="$(XperienceMinimumVersion)" />
    <PackageVersion Include="kentico.xperience.imageprocessing" Version="$(XperienceMinimumVersion)" />
    <PackageVersion Include="kentico.xperience.mjml" Version="$(XperienceMinimumVersion)" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageVersion Include="NUnit" Version="4.3.2" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.7.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="5.0.0" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.20.0.135146" />
  </ItemGroup>
</Project>
